// @generated by protoc-gen-es v2.4.0 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file oaiproto/aisre/agent.proto (package oaiproto.aisre, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Cell } from "../../runme/parser/v1/parser_pb";
import type { ToolCallOutput } from "./notebooks_pb";

/**
 * Describes the file oaiproto/aisre/agent.proto.
 */
export declare const file_oaiproto_aisre_agent: GenFile;

/**
 * @generated from message oaiproto.aisre.GenerateRequest
 */
export declare type GenerateRequest = Message<"oaiproto.aisre.GenerateRequest"> & {
  /**
   * Cells are the context to provide to the AI
   *
   * @generated from field: repeated runme.parser.v1.Cell cells = 1;
   */
  cells: Cell[];

  /**
   * @generated from field: string previous_response_id = 2;
   */
  previousResponseId: string;

  /**
   * openai_access_token is the OpenAI access token to use when contacting the OpenAI API.
   *
   * @generated from field: string openai_access_token = 3;
   */
  openaiAccessToken: string;

  /**
   * model to use. Leave blank to use the default model.
   *
   * @generated from field: string model = 4;
   */
  model: string;

  /**
   * Context specifies how the client is running
   *
   * @generated from field: oaiproto.aisre.GenerateRequest.Context context = 5;
   */
  context: GenerateRequest_Context;

  /**
   * Kernels is a list of the names of the kernels to include
   *
   * @generated from field: repeated string kernels = 6;
   */
  kernels: string[];

  /**
   * Container is the id of an OpenAI container to use
   *
   * @generated from field: string container = 7;
   */
  container: string;

  /**
   * Message is the user message
   *
   * @generated from field: string message = 8;
   */
  message: string;

  /**
   * ToolCalOutputs is the output of the tools calls
   * The tools manipulate the notebook.
   *
   * @generated from field: repeated oaiproto.aisre.ToolCallOutput tool_call_outputs = 9;
   */
  toolCallOutputs: ToolCallOutput[];

  /**
   * Path in the code interpreter container where a copy of the notebook was uploaded
   *
   * @generated from field: string notebook_path = 10;
   */
  notebookPath: string;
};

/**
 * Describes the message oaiproto.aisre.GenerateRequest.
 * Use `create(GenerateRequestSchema)` to create a new message.
 */
export declare const GenerateRequestSchema: GenMessage<GenerateRequest>;

/**
 * Context is the context from which the request is running it impacts how the request is made.
 *
 * @generated from enum oaiproto.aisre.GenerateRequest.Context
 */
export enum GenerateRequest_Context {
  /**
   * @generated from enum value: CONTEXT_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CONTEXT_WEBAPP = 1;
   */
  WEBAPP = 1,

  /**
   * @generated from enum value: CONTEXT_SLACK = 2;
   */
  SLACK = 2,

  /**
   * @generated from enum value: CONTEXT_ALERT_TRIGGERED = 3;
   */
  ALERT_TRIGGERED = 3,
}

/**
 * Describes the enum oaiproto.aisre.GenerateRequest.Context.
 */
export declare const GenerateRequest_ContextSchema: GenEnum<GenerateRequest_Context>;

/**
 * @generated from message oaiproto.aisre.GenerateResponse
 */
export declare type GenerateResponse = Message<"oaiproto.aisre.GenerateResponse"> & {
  /**
   * @generated from field: repeated runme.parser.v1.Cell cells = 1;
   */
  cells: Cell[];

  /**
   * @generated from field: string response_id = 2;
   */
  responseId: string;
};

/**
 * Describes the message oaiproto.aisre.GenerateResponse.
 * Use `create(GenerateResponseSchema)` to create a new message.
 */
export declare const GenerateResponseSchema: GenMessage<GenerateResponse>;

/**
 * MessagesService generates blocks.
 *
 * @generated from service oaiproto.aisre.AgentService
 */
export declare const AgentService: GenService<{
  /**
   * Generate generates cells. Responses are streamed.
   *
   * @generated from rpc oaiproto.aisre.AgentService.Generate
   */
  generate: {
    methodKind: "server_streaming";
    input: typeof GenerateRequestSchema;
    output: typeof GenerateResponseSchema;
  },
}>;

