// @generated by protoc-gen-es v2.4.0 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file oaiproto/aisre/agent.proto (package oaiproto.aisre, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, serviceDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";
import { file_runme_parser_v1_parser } from "../../runme/parser/v1/parser_pb";
import { file_oaiproto_aisre_notebooks } from "./notebooks_pb";

/**
 * Describes the file oaiproto/aisre/agent.proto.
 */
export const file_oaiproto_aisre_agent = /*@__PURE__*/
  fileDesc("ChpvYWlwcm90by9haXNyZS9hZ2VudC5wcm90bxIOb2FpcHJvdG8uYWlzcmUiqgMKD0dlbmVyYXRlUmVxdWVzdBIkCgVjZWxscxgBIAMoCzIVLnJ1bm1lLnBhcnNlci52MS5DZWxsEhwKFHByZXZpb3VzX3Jlc3BvbnNlX2lkGAIgASgJEhsKE29wZW5haV9hY2Nlc3NfdG9rZW4YAyABKAkSDQoFbW9kZWwYBCABKAkSOAoHY29udGV4dBgFIAEoDjInLm9haXByb3RvLmFpc3JlLkdlbmVyYXRlUmVxdWVzdC5Db250ZXh0Eg8KB2tlcm5lbHMYBiADKAkSEQoJY29udGFpbmVyGAcgASgJEg8KB21lc3NhZ2UYCCABKAkSOQoRdG9vbF9jYWxsX291dHB1dHMYCSADKAsyHi5vYWlwcm90by5haXNyZS5Ub29sQ2FsbE91dHB1dBIVCg1ub3RlYm9va19wYXRoGAogASgJImYKB0NvbnRleHQSFwoTQ09OVEVYVF9VTlNQRUNJRklFRBAAEhIKDkNPTlRFWFRfV0VCQVBQEAESEQoNQ09OVEVYVF9TTEFDSxACEhsKF0NPTlRFWFRfQUxFUlRfVFJJR0dFUkVEEAMiTQoQR2VuZXJhdGVSZXNwb25zZRIkCgVjZWxscxgBIAMoCzIVLnJ1bm1lLnBhcnNlci52MS5DZWxsEhMKC3Jlc3BvbnNlX2lkGAIgASgJMmEKDEFnZW50U2VydmljZRJRCghHZW5lcmF0ZRIfLm9haXByb3RvLmFpc3JlLkdlbmVyYXRlUmVxdWVzdBogLm9haXByb3RvLmFpc3JlLkdlbmVyYXRlUmVzcG9uc2UiADABQh5aHGdvLm9wZW5haS5vcmcvb2FpcHJvdG8vYWlzcmViBnByb3RvMw", [file_runme_parser_v1_parser, file_oaiproto_aisre_notebooks]);

/**
 * Describes the message oaiproto.aisre.GenerateRequest.
 * Use `create(GenerateRequestSchema)` to create a new message.
 */
export const GenerateRequestSchema = /*@__PURE__*/
  messageDesc(file_oaiproto_aisre_agent, 0);

/**
 * Describes the enum oaiproto.aisre.GenerateRequest.Context.
 */
export const GenerateRequest_ContextSchema = /*@__PURE__*/
  enumDesc(file_oaiproto_aisre_agent, 0, 0);

/**
 * Context is the context from which the request is running it impacts how the request is made.
 *
 * @generated from enum oaiproto.aisre.GenerateRequest.Context
 */
export const GenerateRequest_Context = /*@__PURE__*/
  tsEnum(GenerateRequest_ContextSchema);

/**
 * Describes the message oaiproto.aisre.GenerateResponse.
 * Use `create(GenerateResponseSchema)` to create a new message.
 */
export const GenerateResponseSchema = /*@__PURE__*/
  messageDesc(file_oaiproto_aisre_agent, 1);

/**
 * MessagesService generates blocks.
 *
 * @generated from service oaiproto.aisre.AgentService
 */
export const AgentService = /*@__PURE__*/
  serviceDesc(file_oaiproto_aisre_agent, 0);

