// @generated by protoc-gen-es v2.4.0 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file oaiproto/aisre/kernels.proto (package oaiproto.aisre, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_runme_parser_v1_parser } from "../../runme/parser/v1/parser_pb";

/**
 * Describes the file oaiproto/aisre/kernels.proto.
 */
export const file_oaiproto_aisre_kernels = /*@__PURE__*/
  fileDesc("ChxvYWlwcm90by9haXNyZS9rZXJuZWxzLnByb3RvEg5vYWlwcm90by5haXNyZSI7ChNFeGVjdXRlQ2VsbHNSZXF1ZXN0EiQKBWNlbGxzGAEgAygLMhUucnVubWUucGFyc2VyLnYxLkNlbGwiPAoURXhlY3V0ZUNlbGxzUmVzcG9uc2USJAoFY2VsbHMYASADKAsyFS5ydW5tZS5wYXJzZXIudjEuQ2VsbDJtCg5LZXJuZWxzU2VydmljZRJbCgxFeGVjdXRlQ2VsbHMSIy5vYWlwcm90by5haXNyZS5FeGVjdXRlQ2VsbHNSZXF1ZXN0GiQub2FpcHJvdG8uYWlzcmUuRXhlY3V0ZUNlbGxzUmVzcG9uc2UiAEIeWhxnby5vcGVuYWkub3JnL29haXByb3RvL2Fpc3JlYgZwcm90bzM", [file_runme_parser_v1_parser]);

/**
 * Describes the message oaiproto.aisre.ExecuteCellsRequest.
 * Use `create(ExecuteCellsRequestSchema)` to create a new message.
 */
export const ExecuteCellsRequestSchema = /*@__PURE__*/
  messageDesc(file_oaiproto_aisre_kernels, 0);

/**
 * Describes the message oaiproto.aisre.ExecuteCellsResponse.
 * Use `create(ExecuteCellsResponseSchema)` to create a new message.
 */
export const ExecuteCellsResponseSchema = /*@__PURE__*/
  messageDesc(file_oaiproto_aisre_kernels, 1);

/**
 * @generated from service oaiproto.aisre.KernelsService
 */
export const KernelsService = /*@__PURE__*/
  serviceDesc(file_oaiproto_aisre_kernels, 0);

