// @generated by protoc-gen-es v2.4.0 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file oaiproto/aisre/kernels.proto (package oaiproto.aisre, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Cell } from "../../runme/parser/v1/parser_pb";

/**
 * Describes the file oaiproto/aisre/kernels.proto.
 */
export declare const file_oaiproto_aisre_kernels: GenFile;

/**
 * @generated from message oaiproto.aisre.ExecuteCellsRequest
 */
export declare type ExecuteCellsRequest = Message<"oaiproto.aisre.ExecuteCellsRequest"> & {
  /**
   * @generated from field: repeated runme.parser.v1.Cell cells = 1;
   */
  cells: Cell[];
};

/**
 * Describes the message oaiproto.aisre.ExecuteCellsRequest.
 * Use `create(ExecuteCellsRequestSchema)` to create a new message.
 */
export declare const ExecuteCellsRequestSchema: GenMessage<ExecuteCellsRequest>;

/**
 * @generated from message oaiproto.aisre.ExecuteCellsResponse
 */
export declare type ExecuteCellsResponse = Message<"oaiproto.aisre.ExecuteCellsResponse"> & {
  /**
   * @generated from field: repeated runme.parser.v1.Cell cells = 1;
   */
  cells: Cell[];
};

/**
 * Describes the message oaiproto.aisre.ExecuteCellsResponse.
 * Use `create(ExecuteCellsResponseSchema)` to create a new message.
 */
export declare const ExecuteCellsResponseSchema: GenMessage<ExecuteCellsResponse>;

/**
 * @generated from service oaiproto.aisre.KernelsService
 */
export declare const KernelsService: GenService<{
  /**
   * @generated from rpc oaiproto.aisre.KernelsService.ExecuteCells
   */
  executeCells: {
    methodKind: "unary";
    input: typeof ExecuteCellsRequestSchema;
    output: typeof ExecuteCellsResponseSchema;
  },
}>;

