// @generated by protoc-gen-es v2.4.0 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file oaiproto/aisre/runs.proto (package oaiproto.aisre, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import type { Notebook } from "../../runme/parser/v1/parser_pb";
import type { ChatkitState, ToolCallOutput } from "./notebooks_pb";

/**
 * Describes the file oaiproto/aisre/runs.proto.
 */
export declare const file_oaiproto_aisre_runs: GenFile;

/**
 * @generated from message oaiproto.aisre.UpdateRunRequest
 */
export declare type UpdateRunRequest = Message<"oaiproto.aisre.UpdateRunRequest"> & {
  /**
   * @generated from field: oaiproto.aisre.Run run = 1;
   */
  run?: Run;
};

/**
 * Describes the message oaiproto.aisre.UpdateRunRequest.
 * Use `create(UpdateRunRequestSchema)` to create a new message.
 */
export declare const UpdateRunRequestSchema: GenMessage<UpdateRunRequest>;

/**
 * @generated from message oaiproto.aisre.UpdateRunResponse
 */
export declare type UpdateRunResponse = Message<"oaiproto.aisre.UpdateRunResponse"> & {
  /**
   * @generated from field: oaiproto.aisre.Run run = 1;
   */
  run?: Run;
};

/**
 * Describes the message oaiproto.aisre.UpdateRunResponse.
 * Use `create(UpdateRunResponseSchema)` to create a new message.
 */
export declare const UpdateRunResponseSchema: GenMessage<UpdateRunResponse>;

/**
 * @generated from message oaiproto.aisre.CreateRunRequest
 */
export declare type CreateRunRequest = Message<"oaiproto.aisre.CreateRunRequest"> & {
  /**
   * @generated from field: oaiproto.aisre.Run run = 1;
   */
  run?: Run;

  /**
   * openai_access_token is the OpenAI access token to use when contacting the OpenAI API.
   *
   * @generated from field: string openai_access_token = 2;
   */
  openaiAccessToken: string;
};

/**
 * Describes the message oaiproto.aisre.CreateRunRequest.
 * Use `create(CreateRunRequestSchema)` to create a new message.
 */
export declare const CreateRunRequestSchema: GenMessage<CreateRunRequest>;

/**
 * @generated from message oaiproto.aisre.CreateRunResponse
 */
export declare type CreateRunResponse = Message<"oaiproto.aisre.CreateRunResponse"> & {
  /**
   * @generated from field: oaiproto.aisre.Run run = 1;
   */
  run?: Run;
};

/**
 * Describes the message oaiproto.aisre.CreateRunResponse.
 * Use `create(CreateRunResponseSchema)` to create a new message.
 */
export declare const CreateRunResponseSchema: GenMessage<CreateRunResponse>;

/**
 * @generated from message oaiproto.aisre.GetRunRequest
 */
export declare type GetRunRequest = Message<"oaiproto.aisre.GetRunRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message oaiproto.aisre.GetRunRequest.
 * Use `create(GetRunRequestSchema)` to create a new message.
 */
export declare const GetRunRequestSchema: GenMessage<GetRunRequest>;

/**
 * @generated from message oaiproto.aisre.GetRunResponse
 */
export declare type GetRunResponse = Message<"oaiproto.aisre.GetRunResponse"> & {
  /**
   * @generated from field: oaiproto.aisre.Run run = 1;
   */
  run?: Run;
};

/**
 * Describes the message oaiproto.aisre.GetRunResponse.
 * Use `create(GetRunResponseSchema)` to create a new message.
 */
export declare const GetRunResponseSchema: GenMessage<GetRunResponse>;

/**
 * @generated from message oaiproto.aisre.ListRunsRequest
 */
export declare type ListRunsRequest = Message<"oaiproto.aisre.ListRunsRequest"> & {
  /**
   * Page is 1-indexed; values < 1 are treated as 1 by the server.
   *
   * @generated from field: int32 page = 1;
   */
  page: number;

  /**
   * Page size controls the number of runs returned per page.
   *
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;

  /**
   * Optional prefix to filter run names. Must match [a-zA-Z0-9_-]+ when set.
   *
   * @generated from field: string query = 3;
   */
  query: string;
};

/**
 * Describes the message oaiproto.aisre.ListRunsRequest.
 * Use `create(ListRunsRequestSchema)` to create a new message.
 */
export declare const ListRunsRequestSchema: GenMessage<ListRunsRequest>;

/**
 * @generated from message oaiproto.aisre.ListRunsResponse
 */
export declare type ListRunsResponse = Message<"oaiproto.aisre.ListRunsResponse"> & {
  /**
   * @generated from field: repeated oaiproto.aisre.RunListItem runs = 1;
   */
  runs: RunListItem[];

  /**
   * @generated from field: int32 page = 2;
   */
  page: number;

  /**
   * @generated from field: int32 page_size = 3;
   */
  pageSize: number;

  /**
   * @generated from field: int32 total_runs = 4;
   */
  totalRuns: number;

  /**
   * @generated from field: string query = 5;
   */
  query: string;
};

/**
 * Describes the message oaiproto.aisre.ListRunsResponse.
 * Use `create(ListRunsResponseSchema)` to create a new message.
 */
export declare const ListRunsResponseSchema: GenMessage<ListRunsResponse>;

/**
 * @generated from message oaiproto.aisre.RunListItem
 */
export declare type RunListItem = Message<"oaiproto.aisre.RunListItem"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: google.protobuf.Timestamp last_updated = 2;
   */
  lastUpdated?: Timestamp;
};

/**
 * Describes the message oaiproto.aisre.RunListItem.
 * Use `create(RunListItemSchema)` to create a new message.
 */
export declare const RunListItemSchema: GenMessage<RunListItem>;

/**
 * @generated from message oaiproto.aisre.ObjectMeta
 */
export declare type ObjectMeta = Message<"oaiproto.aisre.ObjectMeta"> & {
  /**
   * Name of the resource, e.g. "experiment-test".
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Labels are short key value pairs
   *
   * @generated from field: map<string, string> labels = 2;
   */
  labels: { [key: string]: string };

  /**
   * @generated from field: map<string, string> annotations = 3;
   */
  annotations: { [key: string]: string };

  /**
   * resource_version is a server-assigned concurrency token analogous to Kubernetes
   * metadata.resourceVersion.
   *
   * @generated from field: string resource_version = 4;
   */
  resourceVersion: string;
};

/**
 * Describes the message oaiproto.aisre.ObjectMeta.
 * Use `create(ObjectMetaSchema)` to create a new message.
 */
export declare const ObjectMetaSchema: GenMessage<ObjectMeta>;

/**
 * @generated from message oaiproto.aisre.Run
 */
export declare type Run = Message<"oaiproto.aisre.Run"> & {
  /**
   * @generated from field: oaiproto.aisre.ObjectMeta metadata = 1;
   */
  metadata?: ObjectMeta;

  /**
   * notebook stores the notebook associated with this run.
   *
   * @generated from field: runme.parser.v1.Notebook notebook = 2;
   */
  notebook?: Notebook;

  /**
   * @generated from field: repeated oaiproto.aisre.Condition conditions = 4;
   */
  conditions: Condition[];

  /**
   * Pass one or more Alerts (instead of a notebook) and aisre will
   * use it's templated alert behavior
   *
   * @generated from field: repeated oaiproto.aisre.Alert alerts = 5;
   */
  alerts: Alert[];

  /**
   * status carries server-managed runtime details for this run.
   *
   * @generated from field: oaiproto.aisre.RunStatus status = 6;
   */
  status?: RunStatus;

  /**
   * chatkit state stores the status from chatkit
   *
   * @generated from field: oaiproto.aisre.ChatkitState chatkit_state = 7;
   */
  chatkitState?: ChatkitState;

  /**
   * message is the initial message used to trigger this run.
   *
   * @generated from field: string message = 8;
   */
  message: string;

  /**
   * max_turns allows the client to cap the number of agent turns for this run.
   * If unset or <= 0, the server will default to its built-in limit.
   *
   * @generated from field: int32 max_turns = 9;
   */
  maxTurns: number;
};

/**
 * Describes the message oaiproto.aisre.Run.
 * Use `create(RunSchema)` to create a new message.
 */
export declare const RunSchema: GenMessage<Run>;

/**
 * @generated from message oaiproto.aisre.Condition
 */
export declare type Condition = Message<"oaiproto.aisre.Condition"> & {
  /**
   * Type is a string identifying the type of condition e.g. succeeded
   *
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * Reason is the machine readable reason for the condition.
   *
   * @generated from field: string reason = 2;
   */
  reason: string;

  /**
   * Message is the human readable explanation for the condition
   *
   * @generated from field: string message = 3;
   */
  message: string;

  /**
   * @generated from field: oaiproto.aisre.Condition.Status status = 4;
   */
  status: Condition_Status;

  /**
   * @generated from field: google.protobuf.Timestamp last_transition_time = 5;
   */
  lastTransitionTime?: Timestamp;
};

/**
 * Describes the message oaiproto.aisre.Condition.
 * Use `create(ConditionSchema)` to create a new message.
 */
export declare const ConditionSchema: GenMessage<Condition>;

/**
 * Enum
 *
 * @generated from enum oaiproto.aisre.Condition.Status
 */
export enum Condition_Status {
  /**
   * @generated from enum value: STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: STATUS_TRUE = 1;
   */
  TRUE = 1,

  /**
   * @generated from enum value: STATUS_FALSE = 2;
   */
  FALSE = 2,
}

/**
 * Describes the enum oaiproto.aisre.Condition.Status.
 */
export declare const Condition_StatusSchema: GenEnum<Condition_Status>;

/**
 * @generated from message oaiproto.aisre.Alert
 */
export declare type Alert = Message<"oaiproto.aisre.Alert"> & {
  /**
   * @generated from field: string body = 1;
   */
  body: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string source = 3;
   */
  source: string;

  /**
   * @generated from field: string rule_id = 4;
   */
  ruleId: string;

  /**
   * @generated from field: string aggregation_id = 5;
   */
  aggregationId: string;

  /**
   * @generated from field: string instance_id = 6;
   */
  instanceId: string;

  /**
   * @generated from field: google.protobuf.Timestamp triggered_at = 7;
   */
  triggeredAt?: Timestamp;

  /**
   * @generated from field: string slack_channel = 8;
   */
  slackChannel: string;

  /**
   * @generated from field: string slack_thread_timestamp = 9;
   */
  slackThreadTimestamp: string;
};

/**
 * Describes the message oaiproto.aisre.Alert.
 * Use `create(AlertSchema)` to create a new message.
 */
export declare const AlertSchema: GenMessage<Alert>;

/**
 * RunStatus captures the server-managed runtime state for a run.
 *
 * @generated from message oaiproto.aisre.RunStatus
 */
export declare type RunStatus = Message<"oaiproto.aisre.RunStatus"> & {
  /**
   * @generated from field: oaiproto.aisre.RunExecutionState execution_state = 1;
   */
  executionState?: RunExecutionState;
};

/**
 * Describes the message oaiproto.aisre.RunStatus.
 * Use `create(RunStatusSchema)` to create a new message.
 */
export declare const RunStatusSchema: GenMessage<RunStatus>;

/**
 * RunExecutionState holds the information required to resume an interrupted run.
 *
 * @generated from message oaiproto.aisre.RunExecutionState
 */
export declare type RunExecutionState = Message<"oaiproto.aisre.RunExecutionState"> & {
  /**
   * @generated from field: string runner_id = 1;
   */
  runnerId: string;

  /**
   * @generated from field: string previous_response_id = 2;
   */
  previousResponseId: string;

  /**
   * N.B this should no longer be used now that we manipulate the notebook explicitly.
   *
   * @generated from field: repeated string next_cell_ids = 3;
   */
  nextCellIds: string[];

  /**
   * @generated from field: int32 turn = 4;
   */
  turn: number;

  /**
   * @generated from field: google.protobuf.Timestamp lease_expires_at = 5;
   */
  leaseExpiresAt?: Timestamp;

  /**
   * ToolCallOutputs stores the toolcalloutputs that need to be provided on the next response
   *
   * @generated from field: repeated oaiproto.aisre.ToolCallOutput tool_call_outputs = 6;
   */
  toolCallOutputs: ToolCallOutput[];
};

/**
 * Describes the message oaiproto.aisre.RunExecutionState.
 * Use `create(RunExecutionStateSchema)` to create a new message.
 */
export declare const RunExecutionStateSchema: GenMessage<RunExecutionState>;

/**
 * RunsService manages agent runs.
 *
 * Following the Google API Design https://google.aip.dev/133
 * Method names should include the resource name; e.g. CreateRun
 *
 *
 * @generated from service oaiproto.aisre.RunsService
 */
export declare const RunsService: GenService<{
  /**
   * Create creates runs.
   *
   * @generated from rpc oaiproto.aisre.RunsService.CreateRun
   */
  createRun: {
    methodKind: "unary";
    input: typeof CreateRunRequestSchema;
    output: typeof CreateRunResponseSchema;
  },
  /**
   * @generated from rpc oaiproto.aisre.RunsService.GetRun
   */
  getRun: {
    methodKind: "unary";
    input: typeof GetRunRequestSchema;
    output: typeof GetRunResponseSchema;
  },
  /**
   * @generated from rpc oaiproto.aisre.RunsService.UpdateRun
   */
  updateRun: {
    methodKind: "unary";
    input: typeof UpdateRunRequestSchema;
    output: typeof UpdateRunResponseSchema;
  },
  /**
   * ListRuns returns runs using prefix filtering and pagination.
   *
   * @generated from rpc oaiproto.aisre.RunsService.ListRuns
   */
  listRuns: {
    methodKind: "unary";
    input: typeof ListRunsRequestSchema;
    output: typeof ListRunsResponseSchema;
  },
}>;

